#!/bin/bash -e
NAILGUN_DIR=../nailgun-nailgun-all-0.9.1
#KOTLINC_DIR=../kotlinc
#KOTLINC_DIR=~/dev/kotlin/dist/kotlinc
KOTLINC_DIR=~/dev/kotlin-compiler-1.1.3

if [[ `ps aux | grep NGServer | grep -v grep` = "" ]]; then
  echo "Starting Nailgun server..."
  java -Xmx2024M -Xms2024M -verbose:gc \
    -cp $NAILGUN_DIR/nailgun-server/target/classes:$KOTLINC_DIR/lib/kotlin-preloader.jar:$KOTLINC_DIR/lib/kotlin-compiler.jar \
    com.martiansoftware.nailgun.NGServer &
  sleep 1
fi

for HTML in `find src/main/resources/rocker/views -name "*.rocker.html"`; do
  CLASS=$HTML

  # replace src/main/resources/rocker/ with target/classes
  CLASS=${CLASS/src\/main\/resources\/rocker\//target\/classes\/}

  # replace .rocker.html with .class
  CLASS=${CLASS/.rocker.html/.class}

  if [[ $HTML -nt $CLASS ]]; then RECOMPILE_VIEWS=1; fi
done

if [ pom.xml -nt .mvn-classpath ]; then
  rm -f .mvn-classpath
  mvn dependency:build-classpath -Dmdep.outputFile=.mvn-classpath
fi

if [ "$RECOMPILE_VIEWS" != "" ]; then
  echo "Compiling .html to .java"
  time java -cp `cat .mvn-classpath` \
    com.fizzed.rocker.compiler.JavaGeneratorMain

  echo "Compiling .java views to .class"
  time javac \
    -cp /Users/dan/.m2/repository/com/fizzed/rocker-runtime/0.20.0/rocker-runtime-0.20.0.jar \
    target/generated-sources/rocker/views/*.java \
    src/main/java/views/*.java \
    -d target/classes
fi

#  `find src/main/kotlin -name "*.kt"` \
#  `find src/test/kotlin -name "*.kt"` \

for KT in `find src/main/kotlin -name "*.kt"` `find src/test/kotlin -name "*.kt"`; do
  CLASS=$KT

  # replace src/main/kotlin/ with target/classes
  CLASS=${CLASS/src\/main\/kotlin\//target\/classes\/}

  # replace src/test/kotlin/ with target/classes
  CLASS=${CLASS/src\/test\/kotlin\//target\/classes\/}

  if [[ $KT -nt ${CLASS/.kt/.class} && $KT -nt ${CLASS/.kt/Kt.class} ]]; then
    KTS="$KTS $KT"
  fi
done

if [ "$KTS" != "" ]; then
  echo "Compiling .kt to .class"
  echo $KTS
  time $NAILGUN_DIR/ng \
    org.jetbrains.kotlin.preloading.Preloader \
    org.jetbrains.kotlin.cli.jvm.K2JVMCompiler \
    $KTS \
    -d $PWD/target/classes \
    -cp `cat .mvn-classpath`:target/classes
fi

if [ "$1" == "scrape" ]; then
  java -cp $(cat .mvn-classpath):target/classes \
    integration_test.ScrapeOldServerKt
elif [ "$1" == "compare" ]; then
  java -cp $(cat .mvn-classpath):target/classes \
    integration_test.IntegrationTestKt
elif [ "$1" == "serve" ]; then
  java -cp $(cat .mvn-classpath):target/classes \
    webapp.WebServerKt
fi
